USE [master]
GO

/****** Object:  Database [gym]    Script Date: 17.06.2024 21:38:21 ******/
DROP DATABASE [gym]
GO

/****** Object:  Database [gym]    Script Date: 17.06.2024 21:38:21 ******/
CREATE DATABASE [gym]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'gym', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\gym.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'gym_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\gym_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [gym].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [gym] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [gym] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [gym] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [gym] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [gym] SET ARITHABORT OFF 
GO

ALTER DATABASE [gym] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [gym] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [gym] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [gym] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [gym] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [gym] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [gym] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [gym] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [gym] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [gym] SET  ENABLE_BROKER 
GO

ALTER DATABASE [gym] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [gym] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [gym] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [gym] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [gym] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [gym] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [gym] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [gym] SET RECOVERY FULL 
GO

ALTER DATABASE [gym] SET  MULTI_USER 
GO

ALTER DATABASE [gym] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [gym] SET DB_CHAINING OFF 
GO

ALTER DATABASE [gym] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [gym] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [gym] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [gym] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [gym] SET QUERY_STORE = ON
GO

ALTER DATABASE [gym] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [gym] SET  READ_WRITE 
GO

